/* ==========================================================================
   Mero Upload Content Studio (Dual Mode)
   1. Direct File Upload -> Bunny.net Stream (HLS, global CDN, adult-OK)
   2. Embed Stream Link  -> Zero-Host Iframe Protocol (YouTube/Vimeo/Dailymotion)
   ========================================================================== */

// ── Bunny.net Stream Configuration ──────────────────────────────────────────
// IMPORTANT: Rotate your API key in Bunny dashboard after setup is complete.
// In production, move this to a backend endpoint so the key is never public.
const BUNNY_LIBRARY_ID = "759040";
const BUNNY_API_KEY = "d06ec310-5582-4578-8a1f461d3557-2965-4b78";
const BUNNY_API_BASE = "https://video.bunnycdn.com/library";
const BUNNY_CDN_HOST = "https://vz-95ca6a68-303.b-cdn.net"; // Dedicated Pull Zone CDN hostname

class MeroUploadManager {
  constructor() {
    this.modal = null;
    this.form = null;
    this.currentMode = "file"; // "file" | "embed"
    this.selectedVideoFile = null;
    this.autoGeneratedThumbnail = "";
    this.detectedDuration = 120;
    this.uploadTask = null;
    this.isUploading = false;

    // Tags State (Multiple tags from Firestore)
    this.selectedTags = new Set();
    this.availableTags = [];

    // 6-Frame Thumbnail Previews State
    this.capturedThumbnails = [];
    this.selectedThumbnailUrl = "";
    this.selectedThumbnailIndex = -1;
  }

  init() {
    this.modal = document.getElementById("uploadModal");
    this.form = document.getElementById("uploadForm");
    this.bindEvents();
    this.bindTagSelector();
    this.bindThumbnailPicker();
    this.switchMode("file");
    this.loadAvailableTags();
  }

  handleUploadTrigger() {
    const user = window.meroAuth?.currentUser;
    if (!user) {
      if (typeof window.openAuthModal === "function") {
        window.openAuthModal("Sign in to upload and share your videos on Mero.", () => {
          this.openModal();
        });
      } else if (window.meroAuth?.openAuthModal) {
        window.meroAuth.openAuthModal("Sign in to upload and share your videos on Mero.", () => {
          this.openModal();
        });
      } else {
        const modal = document.getElementById("authModal");
        if (modal) {
          modal.classList.add("active");
          document.body.classList.add("modal-open");
        }
      }
      return;
    }
    this.openModal();
  }

  openModal() {
    this.modal = this.modal || document.getElementById("uploadModal");
    if (this.modal) {
      this.modal.classList.add("active");
      document.body.classList.add("modal-open");
    }
    this.loadAvailableTags();
  }

  closeModal() {
    if (this.uploadTask && typeof this.uploadTask.abort === "function") {
      this.uploadTask.abort();
    }
    this.uploadTask = null;
    this.isUploading = false;

    this.modal = this.modal || document.getElementById("uploadModal");
    if (this.modal) {
      this.modal.classList.remove("active");
      document.body.classList.remove("modal-open");
    }
    this.clearSelectedFile();
    this.selectedTags.clear();
    this.renderSelectedTags();
    this.renderAvailableTags();
    this.hideProgressBar();

    const providerPill = document.getElementById("urlProviderPill");
    if (providerPill) providerPill.style.display = "none";
    const urlSubhint = document.getElementById("urlSubhint");
    if (urlSubhint) urlSubhint.textContent = "Supports YouTube, Vimeo, Dailymotion";

    const customWrap = document.getElementById("customThumbUrlWrap");
    if (customWrap) customWrap.style.display = "none";
    const toggleBtn = document.getElementById("toggleCustomThumbBtn");
    if (toggleBtn) toggleBtn.textContent = "+ Custom URL";

    const submitBtn = document.getElementById("uploadSubmitBtn");
    if (submitBtn) {
      submitBtn.disabled = false;
      submitBtn.textContent = "Upload Video";
    }

    if (this.form) this.form.reset();
    this.switchMode("file");
  }

  bindEvents() {
    // Global Studio & Upload Triggers
    const triggerIds = ["topUploadBtn", "sidebarStudioBtn", "mobileUploadBtn", "dropdownUploadBtn", "emptyUploadFirstVideoBtn"];
    triggerIds.forEach(id => {
      const btn = document.getElementById(id);
      if (btn) {
        btn.addEventListener("click", (e) => {
          e.preventDefault();
          this.handleUploadTrigger();
        });
      }
    });

    // Mode Switcher Tabs
    const tabUploadFile = document.getElementById("tabUploadFile");
    const tabEmbedLink = document.getElementById("tabEmbedLink");

    if (tabUploadFile) {
      tabUploadFile.addEventListener("click", () => this.switchMode("file"));
    }
    if (tabEmbedLink) {
      tabEmbedLink.addEventListener("click", () => this.switchMode("embed"));
    }

    // Modal Close
    const closeBtn = document.getElementById("uploadModalCloseBtn");
    if (closeBtn && this.modal) {
      closeBtn.addEventListener("click", () => this.closeModal());
    }

    if (this.modal) {
      this.modal.addEventListener("click", (e) => {
        if (e.target === this.modal && !this.isUploading) this.closeModal();
      });
    }

    // Dropzone & File Selection
    const dropzone = document.getElementById("uploadDropzone");
    const fileInput = document.getElementById("uploadVideoFile");
    const clearFileBtn = document.getElementById("clearFileBtn");

    if (dropzone && fileInput) {
      dropzone.addEventListener("click", (e) => {
        if (!e.target.closest("#clearFileBtn") && !this.isUploading) {
          fileInput.click();
        }
      });

      // Drag & drop
      ["dragenter", "dragover"].forEach(evtName => {
        dropzone.addEventListener(evtName, (e) => {
          e.preventDefault();
          e.stopPropagation();
          if (!this.isUploading) dropzone.classList.add("dragover");
        });
      });

      ["dragleave", "drop"].forEach(evtName => {
        dropzone.addEventListener(evtName, (e) => {
          e.preventDefault();
          e.stopPropagation();
          dropzone.classList.remove("dragover");
        });
      });

      dropzone.addEventListener("drop", (e) => {
        if (this.isUploading) return;
        const files = e.dataTransfer?.files;
        if (files && files.length > 0) {
          this.handleFileSelected(files[0]);
        }
      });

      fileInput.addEventListener("change", (e) => {
        if (e.target.files && e.target.files.length > 0) {
          this.handleFileSelected(e.target.files[0]);
        }
      });
    }

    if (clearFileBtn) {
      clearFileBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.clearSelectedFile();
      });
    }

    // Embed URL Provider Detection & Auto Thumbnail Fetch
    const urlInput = document.getElementById("uploadVideoUrl");
    const providerPill = document.getElementById("urlProviderPill");
    const urlSubhint = document.getElementById("urlSubhint");
    const thumbInput = document.getElementById("uploadThumbUrl");

    if (urlInput) {
      urlInput.addEventListener("input", (e) => {
        const val = e.target.value.trim();
        if (!val) {
          if (providerPill) providerPill.style.display = "none";
          if (urlSubhint) urlSubhint.textContent = "Supports YouTube, Vimeo, Dailymotion, or public iframe embed streams";
          return;
        }

        const parsed = this.parseEmbedUrl(val);
        if (providerPill) {
          providerPill.textContent = parsed.providerName;
          providerPill.className = `provider-pill ${parsed.provider}`;
          providerPill.style.display = "inline-flex";
        }
        if (urlSubhint) {
          urlSubhint.textContent = `✓ Stream will be rendered securely via ${parsed.providerName} iframe embed`;
        }

        // Auto-populate thumbnail if provider has a default poster
        if (parsed.defaultThumbnail) {
          this.renderEmbedThumbnailCard(parsed.defaultThumbnail, parsed.providerName);
          if (thumbInput && !thumbInput.value) {
            thumbInput.value = parsed.defaultThumbnail;
          }
        }
      });
    }

    // Form Submit
    if (this.form) {
      this.form.addEventListener("submit", (e) => this.handleSubmit(e));
    }
  }

  switchMode(mode) {
    this.currentMode = mode;
    const tabUploadFile = document.getElementById("tabUploadFile");
    const tabEmbedLink = document.getElementById("tabEmbedLink");
    const panelUpload = document.getElementById("studioUploadPanel");
    const panelEmbed = document.getElementById("studioEmbedPanel");
    const submitBtn = document.getElementById("uploadSubmitBtn");
    const urlInput = document.getElementById("uploadVideoUrl");

    if (mode === "file") {
      if (tabUploadFile) {
        tabUploadFile.classList.add("active");
        tabUploadFile.setAttribute("aria-selected", "true");
      }
      if (tabEmbedLink) {
        tabEmbedLink.classList.remove("active");
        tabEmbedLink.setAttribute("aria-selected", "false");
      }
      if (panelUpload) panelUpload.style.display = "flex";
      if (panelEmbed) panelEmbed.style.display = "none";
      if (urlInput) urlInput.removeAttribute("required");
      if (submitBtn && !this.isUploading) {
        submitBtn.textContent = "Upload Video";
      }
    } else {
      if (tabEmbedLink) {
        tabEmbedLink.classList.add("active");
        tabEmbedLink.setAttribute("aria-selected", "true");
      }
      if (tabUploadFile) {
        tabUploadFile.classList.remove("active");
        tabUploadFile.setAttribute("aria-selected", "false");
      }
      if (panelEmbed) panelEmbed.style.display = "flex";
      if (panelUpload) panelUpload.style.display = "none";
      if (urlInput) urlInput.setAttribute("required", "required");
      if (submitBtn && !this.isUploading) {
        submitBtn.textContent = "Embed & Publish Video";
      }
    }
  }

  handleFileSelected(file) {
    if (!file) return;

    // Validate video file
    const isVideo = file.type.startsWith("video/") || /\.(mp4|webm|mov|ogg|m4v)$/i.test(file.name);
    if (!isVideo) {
      window.showToast("Please choose a valid video file (.mp4, .webm, .mov)");
      return;
    }

    this.selectedVideoFile = file;

    // Display selected file card
    const emptyState = document.getElementById("dropzoneEmptyState");
    const selectedState = document.getElementById("dropzoneSelectedFile");
    const nameEl = document.getElementById("selectedFileName");
    const metaEl = document.getElementById("selectedFileMeta");

    if (emptyState) emptyState.style.display = "none";
    if (selectedState) selectedState.style.display = "flex";
    if (nameEl) nameEl.textContent = file.name;
    if (metaEl) metaEl.textContent = `${this.formatFileSize(file.size)} • Reading media metadata...`;

    // Auto-fill title if empty
    const titleInput = document.getElementById("uploadTitle");
    if (titleInput && !titleInput.value.trim()) {
      const cleanName = file.name
        .replace(/\.[^/.]+$/, "")
        .replace(/[-_]+/g, " ")
        .replace(/\b\w/g, l => l.toUpperCase());
      titleInput.value = cleanName;
    }

    // Generate 6 thumbnail frame previews from video
    this.generateThumbnailOptions(file);
  }

  clearSelectedFile() {
    this.selectedVideoFile = null;
    this.autoGeneratedThumbnail = "";
    this.capturedThumbnails = [];
    this.selectedThumbnailUrl = "";
    this.selectedThumbnailIndex = -1;

    const fileInput = document.getElementById("uploadVideoFile");
    if (fileInput) fileInput.value = "";

    const emptyState = document.getElementById("dropzoneEmptyState");
    const selectedState = document.getElementById("dropzoneSelectedFile");
    if (emptyState) emptyState.style.display = "flex";
    if (selectedState) selectedState.style.display = "none";

    const thumbGrid = document.getElementById("thumbnailPreviewsGrid");
    if (thumbGrid) {
      thumbGrid.innerHTML = `
        <div class="thumb-empty-hint" id="thumbEmptyHint">
          <span>Select a video to generate preview thumbnails</span>
        </div>
      `;
    }

    const thumbInput = document.getElementById("uploadThumbUrl");
    if (thumbInput) thumbInput.value = "";
  }

  // --- Tag Selector Methods (Firestore Collection) ---
  bindTagSelector() {
    const customInput = document.getElementById("tagCustomInput");
    if (!customInput) return;

    customInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === ",") {
        e.preventDefault();
        const val = customInput.value.trim();
        if (val) {
          this.addCustomTag(val);
          customInput.value = "";
        }
      }
    });

    customInput.addEventListener("blur", () => {
      const val = customInput.value.trim();
      if (val) {
        this.addCustomTag(val);
        customInput.value = "";
      }
    });
  }

  async loadAvailableTags() {
    try {
      if (window.meroDb && typeof window.meroDb.getTags === "function") {
        this.availableTags = await window.meroDb.getTags();
      } else {
        this.availableTags = ["Gaming", "Tech", "Coding", "Lo-Fi", "Design", "Tutorial", "AI", "Music", "Animation", "Vlog", "Podcast", "Entertainment"];
      }
    } catch (e) {
      console.warn("Could not load tags from Firestore:", e);
      this.availableTags = ["Gaming", "Tech", "Coding", "Lo-Fi", "Design", "Tutorial", "AI", "Music", "Animation", "Vlog", "Podcast", "Entertainment"];
    }
    this.renderAvailableTags();
  }

  renderAvailableTags() {
    const listEl = document.getElementById("availableTagsList");
    if (!listEl) return;
    listEl.innerHTML = "";

    if (!this.availableTags || this.availableTags.length === 0) {
      listEl.innerHTML = `<span style="font-size: 11px; color: var(--text-dimmed); font-style: italic;">No tags found.</span>`;
      this.renderSelectedTags();
      return;
    }

    // Separate selected vs unselected so selected tags appear prominently first
    const selected = [];
    const unselected = [];
    this.availableTags.forEach(tagName => {
      if (this.selectedTags.has(tagName.toLowerCase())) {
        selected.push(tagName);
      } else {
        unselected.push(tagName);
      }
    });

    const orderedTags = [...selected, ...unselected];

    orderedTags.forEach(tagName => {
      const isSelected = this.selectedTags.has(tagName.toLowerCase());
      const btn = document.createElement("button");
      btn.type = "button";
      btn.className = `tag-pick-btn ${isSelected ? "is-selected" : ""}`;
      btn.setAttribute("aria-pressed", isSelected ? "true" : "false");

      if (isSelected) {
        btn.innerHTML = `<span class="tag-status-icon">✓</span> <span class="tag-name">${tagName}</span> <span class="tag-remove-icon" title="Deselect tag">&times;</span>`;
      } else {
        btn.innerHTML = `<span class="tag-status-icon">+</span> <span class="tag-name">${tagName}</span>`;
      }

      btn.addEventListener("click", () => {
        this.toggleTag(tagName);
      });
      listEl.appendChild(btn);
    });

    this.renderSelectedTags();
  }

  toggleTag(tagName) {
    if (!tagName) return;
    const clean = tagName.replace(/^#+/, "").trim();
    const key = clean.toLowerCase();
    if (this.selectedTags.has(key)) {
      this.selectedTags.delete(key);
    } else {
      this.selectedTags.add(key);
    }
    this.renderAvailableTags();
  }

  addCustomTag(rawText) {
    if (!rawText) return;
    const items = rawText.split(/[,\s]+/).map(t => t.replace(/^#+/, "").trim()).filter(Boolean);
    items.forEach(clean => {
      const key = clean.toLowerCase();
      const formatted = clean.charAt(0).toUpperCase() + clean.slice(1);
      this.selectedTags.add(key);
      if (!this.availableTags.some(t => t.toLowerCase() === key)) {
        this.availableTags.unshift(formatted);
        if (window.meroDb?.addTag) {
          window.meroDb.addTag(formatted).catch(() => {});
        }
      }
    });
    this.renderAvailableTags();
  }

  removeTag(key) {
    this.selectedTags.delete(key.toLowerCase());
    this.renderAvailableTags();
  }

  renderSelectedTags() {
    const countEl = document.getElementById("selectedTagsCount");
    if (countEl) {
      const count = this.selectedTags.size;
      countEl.textContent = `${count} selected`;
    }
  }

  // --- 6 Image Thumbnail Previews Methods ---
  bindThumbnailPicker() {
    const toggleBtn = document.getElementById("toggleCustomThumbBtn");
    const customWrap = document.getElementById("customThumbUrlWrap");
    const thumbInput = document.getElementById("uploadThumbUrl");

    if (toggleBtn && customWrap) {
      toggleBtn.addEventListener("click", () => {
        const isHidden = customWrap.style.display === "none";
        customWrap.style.display = isHidden ? "block" : "none";
        toggleBtn.textContent = isHidden ? "✕ Hide Custom URL" : "+ Custom URL";
      });
    }

    if (thumbInput) {
      thumbInput.addEventListener("input", () => {
        const val = thumbInput.value.trim();
        if (val) {
          this.selectedThumbnailUrl = val;
          const grid = document.getElementById("thumbnailPreviewsGrid");
          grid?.querySelectorAll(".thumb-preview-card").forEach(c => c.classList.remove("is-selected"));
        }
      });
    }
  }

  renderThumbnailSkeletons() {
    const grid = document.getElementById("thumbnailPreviewsGrid");
    if (!grid) return;
    grid.innerHTML = "";
    for (let i = 0; i < 6; i++) {
      const card = document.createElement("div");
      card.className = "thumb-preview-card thumb-skeleton";
      card.innerHTML = `<div class="skeleton-thumb shimmer" style="width: 100%; height: 100%;"></div>`;
      grid.appendChild(card);
    }
  }

  async generateThumbnailOptions(file) {
    const grid = document.getElementById("thumbnailPreviewsGrid");
    if (!grid) return;

    this.renderThumbnailSkeletons();
    this.capturedThumbnails = [];

    const tempUrl = URL.createObjectURL(file);
    const tempVideo = document.createElement("video");
    tempVideo.preload = "auto";
    tempVideo.src = tempUrl;
    tempVideo.muted = true;
    tempVideo.playsInline = true;

    try {
      await new Promise((resolve, reject) => {
        const timeout = setTimeout(() => resolve(), 6000);
        tempVideo.onloadedmetadata = () => {
          clearTimeout(timeout);
          resolve();
        };
        tempVideo.onerror = (e) => reject(e);
      });

      const dur = tempVideo.duration || 60;
      this.detectedDuration = Math.round(dur);
      const metaEl = document.getElementById("selectedFileMeta");
      if (metaEl) {
        metaEl.textContent = `${this.formatFileSize(file.size)} • ${this.formatDuration(dur)}`;
      }

      // Calculate 6 timestamps spread evenly across the video
      const fractions = [0.08, 0.24, 0.40, 0.58, 0.74, 0.90];
      const timestamps = fractions.map(f => Math.min(Math.max(0.5, dur * f), Math.max(0.5, dur - 0.5)));

      const canvas = document.createElement("canvas");
      const ctx = canvas.getContext("2d");

      for (let i = 0; i < timestamps.length; i++) {
        const time = timestamps[i];
        try {
          await new Promise((resolve) => {
            const seekTimeout = setTimeout(() => resolve(), 2500);
            tempVideo.onseeked = () => {
              clearTimeout(seekTimeout);
              try {
                canvas.width = tempVideo.videoWidth || 640;
                canvas.height = tempVideo.videoHeight || 360;
                ctx.drawImage(tempVideo, 0, 0, canvas.width, canvas.height);
                const dataUrl = canvas.toDataURL("image/jpeg", 0.85);
                this.capturedThumbnails.push({
                  dataUrl,
                  timestamp: time,
                  formattedTime: this.formatDuration(time)
                });
              } catch (err) {
                console.warn("Frame draw error:", err);
              }
              resolve();
            };
            tempVideo.currentTime = time;
          });
        } catch (e) {
          console.warn("Seek error:", e);
        }
      }

    } catch (err) {
      console.warn("Thumbnail generation error:", err);
    } finally {
      URL.revokeObjectURL(tempUrl);
    }

    if (this.capturedThumbnails.length > 0) {
      // Pick 2nd frame (index 1) or 1st as default
      this.selectedThumbnailIndex = this.capturedThumbnails.length > 1 ? 1 : 0;
      this.selectedThumbnailUrl = this.capturedThumbnails[this.selectedThumbnailIndex].dataUrl;
      this.autoGeneratedThumbnail = this.selectedThumbnailUrl;
      this.renderThumbnailCards();
    } else {
      grid.innerHTML = `
        <div class="thumb-empty-hint">
          <svg class="icon" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
          <span>Could not extract frames. Please provide a custom thumbnail URL.</span>
        </div>
      `;
    }
  }

  renderThumbnailCards() {
    const grid = document.getElementById("thumbnailPreviewsGrid");
    if (!grid) return;
    grid.innerHTML = "";

    this.capturedThumbnails.forEach((item, index) => {
      const isSelected = index === this.selectedThumbnailIndex;
      const card = document.createElement("div");
      card.className = `thumb-preview-card ${isSelected ? "is-selected" : ""}`;
      card.title = `Click to choose frame at ${item.formattedTime} as thumbnail`;
      card.innerHTML = `
        <img class="thumb-preview-img" src="${item.dataUrl}" alt="Thumbnail option ${index + 1}" />
        <span class="thumb-preview-time">${item.formattedTime}</span>
        <div class="thumb-selected-badge">
          <svg viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg>
        </div>
      `;

      card.addEventListener("click", () => {
        this.selectedThumbnailIndex = index;
        this.selectedThumbnailUrl = item.dataUrl;
        this.autoGeneratedThumbnail = item.dataUrl;
        const customThumbInput = document.getElementById("uploadThumbUrl");
        if (customThumbInput) customThumbInput.value = "";
        grid.querySelectorAll(".thumb-preview-card").forEach((c, i) => {
          c.classList.toggle("is-selected", i === index);
        });
        window.showToast(`Selected frame at ${item.formattedTime} as thumbnail`);
      });

      grid.appendChild(card);
    });
  }

  renderEmbedThumbnailCard(thumbUrl, providerName) {
    const grid = document.getElementById("thumbnailPreviewsGrid");
    if (!grid || !thumbUrl) return;
    grid.innerHTML = "";
    this.selectedThumbnailUrl = thumbUrl;
    this.selectedThumbnailIndex = 0;

    const card = document.createElement("div");
    card.className = "thumb-preview-card is-selected";
    card.style.gridColumn = "1 / -1";
    card.style.maxHeight = "160px";
    card.innerHTML = `
      <img class="thumb-preview-img" src="${thumbUrl}" alt="${providerName} Poster" />
      <span class="thumb-preview-time">${providerName} Poster</span>
      <div class="thumb-selected-badge">
        <svg viewBox="0 0 24 24"><polyline points="20 6 9 17 4 12"></polyline></svg>
      </div>
    `;
    grid.appendChild(card);
  }

  parseEmbedUrl(url) {
    if (!url) return { isEmbed: true, provider: "iframe", providerName: "Web Embed", embedUrl: "" };
    url = url.trim();

    // YouTube: watch?v=ID, youtu.be/ID, shorts/ID, embed/ID
    const ytMatch = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/|v\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/i);
    if (ytMatch && ytMatch[1]) {
      const id = ytMatch[1];
      return {
        isEmbed: true,
        provider: "youtube",
        providerName: "YouTube",
        videoId: id,
        embedUrl: `https://www.youtube-nocookie.com/embed/${id}?autoplay=1&enablejsapi=1&rel=0`,
        defaultThumbnail: `https://img.youtube.com/vi/${id}/hqdefault.jpg`
      };
    }

    // Vimeo: vimeo.com/ID
    const vimeoMatch = url.match(/vimeo\.com\/(?:video\/)?(\d+)/i);
    if (vimeoMatch && vimeoMatch[1]) {
      const id = vimeoMatch[1];
      return {
        isEmbed: true,
        provider: "vimeo",
        providerName: "Vimeo",
        videoId: id,
        embedUrl: `https://player.vimeo.com/video/${id}?autoplay=1`,
        defaultThumbnail: ""
      };
    }

    // Dailymotion: dailymotion.com/video/ID
    const dmMatch = url.match(/dailymotion\.com\/video\/([a-zA-Z0-9]+)/i);
    if (dmMatch && dmMatch[1]) {
      const id = dmMatch[1];
      return {
        isEmbed: true,
        provider: "dailymotion",
        providerName: "Dailymotion",
        videoId: id,
        embedUrl: `https://www.dailymotion.com/embed/video/${id}?autoplay=1`,
        defaultThumbnail: `https://www.dailymotion.com/thumbnail/video/${id}`
      };
    }

    // Direct MP4 / WebM video link
    if (/\.(mp4|webm|ogg|m3u8)(\?.*)?$/i.test(url)) {
      return {
        isEmbed: false,
        provider: "direct",
        providerName: "Direct Stream",
        embedUrl: url,
        defaultThumbnail: ""
      };
    }

    // Generic iframe embed URL
    return {
      isEmbed: true,
      provider: "iframe",
      providerName: "Iframe Embed",
      embedUrl: url,
      defaultThumbnail: ""
    };
  }

  showProgressBar() {
    const bar = document.getElementById("uploadProgressContainer");
    if (bar) bar.style.display = "flex";
  }

  hideProgressBar() {
    const bar = document.getElementById("uploadProgressContainer");
    const fill = document.getElementById("uploadProgressBarFill");
    const percent = document.getElementById("uploadProgressPercent");
    if (bar) bar.style.display = "none";
    if (fill) fill.style.width = "0%";
    if (percent) percent.textContent = "0%";
  }

  updateProgress(percentValue, transferred, total) {
    const fill = document.getElementById("uploadProgressBarFill");
    const percentEl = document.getElementById("uploadProgressPercent");
    const statusEl = document.getElementById("uploadProgressStatus");
    const submitBtn = document.getElementById("uploadSubmitBtn");

    const pct = Math.min(100, Math.max(0, Math.round(percentValue)));
    if (fill) fill.style.width = `${pct}%`;
    if (percentEl) percentEl.textContent = `${pct}%`;
    if (submitBtn) {
      submitBtn.textContent = `Uploading video... ${pct}%`;
    }
    if (statusEl && total > 0) {
      statusEl.innerHTML = `
        <svg class="icon spin" style="width: 14px; height: 14px;" viewBox="0 0 24 24"><line x1="12" y1="2" x2="12" y2="6"></line><line x1="12" y1="18" x2="12" y2="22"></line><line x1="4.93" y1="4.93" x2="7.76" y2="7.76"></line><line x1="16.24" y1="16.24" x2="19.07" y2="19.07"></line><line x1="2" y1="12" x2="6" y2="12"></line><line x1="18" y1="12" x2="22" y2="12"></line><line x1="4.93" y1="19.07" x2="7.76" y2="16.24"></line><line x1="16.24" y1="7.76" x2="19.07" y2="4.93"></line></svg>
        <span>Uploading: ${(transferred / (1024 * 1024)).toFixed(1)} MB / ${(total / (1024 * 1024)).toFixed(1)} MB (${pct}%)</span>
      `;
    }
  }

  async handleSubmit(e) {
    e.preventDefault();
    const user = window.meroAuth?.currentUser;
    if (!user) {
      window.meroAuth?.openAuthModal();
      return;
    }

    const title = document.getElementById("uploadTitle")?.value.trim();
    const pendingTag = document.getElementById("tagCustomInput")?.value.trim();
    if (pendingTag) {
      this.addCustomTag(pendingTag);
      const tagInp = document.getElementById("tagCustomInput");
      if (tagInp) tagInp.value = "";
    }

    const description = document.getElementById("uploadDescription")?.value.trim() || "";
    const customThumbUrl = document.getElementById("uploadThumbUrl")?.value.trim();
    const submitBtn = document.getElementById("uploadSubmitBtn");

    // Combine selected tags from multi-tag picker and any hashtags in description
    const descTags = (description.match(/#[a-zA-Z0-9_]+/g) || [])
      .map(t => t.replace(/^#+/, "").trim().toLowerCase())
      .filter(Boolean);

    const mergedTags = new Set([...this.selectedTags, ...descTags]);
    if (mergedTags.size === 0) {
      mergedTags.add("general");
    }
    const tags = Array.from(mergedTags);
    const category = tags[0].charAt(0).toUpperCase() + tags[0].slice(1);

    if (!title) {
      window.showToast("Please enter a video title");
      return;
    }

    // ------------------------------------------------------------------------
    // CASE 1: File Upload → Bunny.net Stream (HLS, global CDN)
    // ------------------------------------------------------------------------
    if (this.currentMode === "file") {
      if (!this.selectedVideoFile) {
        window.showToast("Please choose or drag a video file to upload");
        return;
      }

      const file = this.selectedVideoFile;
      const finalThumbnail = customThumbUrl || this.selectedThumbnailUrl || this.autoGeneratedThumbnail || window.generateAutoThumbnail(title, category);

      this.isUploading = true;
      if (submitBtn) {
        submitBtn.disabled = true;
        submitBtn.textContent = "Uploading video... 0%";
      }
      this.showProgressBar();

      try {
        // ── Step 1: Create a new video entry in Bunny Stream library ────────
        const createRes = await fetch(
          `${BUNNY_API_BASE}/${BUNNY_LIBRARY_ID}/videos`,
          {
            method: "POST",
            headers: {
              "AccessKey": BUNNY_API_KEY,
              "Content-Type": "application/json"
            },
            body: JSON.stringify({ title })
          }
        );

        if (!createRes.ok) {
          const errText = await createRes.text();
          throw new Error(`Bunny create video failed: ${createRes.status} — ${errText}`);
        }

        const { guid: videoId } = await createRes.json();
        if (!videoId) throw new Error("Bunny did not return a video ID.");

        // ── Step 2: Upload raw file bytes to Bunny (XHR for progress bar) ──
        await new Promise((resolve, reject) => {
          const xhr = new XMLHttpRequest();
          // Store reference so closeModal() can abort it
          this.uploadTask = xhr;

          xhr.open("PUT", `${BUNNY_API_BASE}/${BUNNY_LIBRARY_ID}/videos/${videoId}`);
          xhr.setRequestHeader("AccessKey", BUNNY_API_KEY);
          xhr.setRequestHeader("Content-Type", "application/octet-stream");

          xhr.upload.onprogress = (evt) => {
            if (evt.lengthComputable) {
              const pct = (evt.loaded / evt.total) * 100;
              this.updateProgress(pct, evt.loaded, evt.total);
            }
          };

          xhr.onload = () => {
            if (xhr.status >= 200 && xhr.status < 300) {
              resolve();
            } else {
              reject(new Error(`Upload failed: server returned ${xhr.status}. Check your API key.`));
            }
          };

          xhr.onerror = () => reject(new Error("Network error — check your internet connection."));
          xhr.onabort = () => reject(new Error("Upload cancelled."));

          // Send raw bytes — no Content-Type override to avoid CORS preflight issues
          xhr.send(file);
        });

        // ── Show "Publishing" status after bytes are sent ────────────────────
        const statusEl = document.getElementById("uploadProgressStatus");
        if (statusEl) {
          statusEl.innerHTML = `
            <svg class="icon spin" style="width: 14px; height: 14px;" viewBox="0 0 24 24"><line x1="12" y1="2" x2="12" y2="6"></line><line x1="12" y1="18" x2="12" y2="22"></line><line x1="4.93" y1="4.93" x2="7.76" y2="7.76"></line><line x1="16.24" y1="16.24" x2="19.07" y2="19.07"></line><line x1="2" y1="12" x2="6" y2="12"></line><line x1="18" y1="12" x2="22" y2="12"></line><line x1="4.93" y1="19.07" x2="7.76" y2="16.24"></line><line x1="16.24" y1="7.76" x2="19.07" y2="4.93"></line></svg>
            <span>Publishing video...</span>
          `;
        }
        if (submitBtn) {
          submitBtn.textContent = "Publishing video...";
        }

        // ── Step 3: Build playback URLs ─────────────────────────────────────
        let activeCdnHost = BUNNY_CDN_HOST;
        try {
          const checkRes = await fetch(`${BUNNY_API_BASE}/${BUNNY_LIBRARY_ID}/videos/${videoId}`, {
            headers: { "AccessKey": BUNNY_API_KEY }
          });
          if (checkRes.ok) {
            const vidMeta = await checkRes.json();
            if (vidMeta.thumbnailUrl) {
              activeCdnHost = new URL(vidMeta.thumbnailUrl).origin;
            }
          }
        } catch (e) {
          console.warn("CDN domain check warning:", e);
        }

        // HLS stream  → plays in <video> element via hls.js or native Safari
        const hlsUrl = `${activeCdnHost}/${videoId}/playlist.m3u8`;
        // Embed iframe → fallback for browsers without HLS support
        const embedUrl = `https://iframe.mediadelivery.net/embed/${BUNNY_LIBRARY_ID}/${videoId}?autoplay=true&loop=false&muted=false&preload=true`;
        // Auto-thumbnail from Bunny (generated after processing, may take ~30s)
        const bunnyThumb = `${activeCdnHost}/${videoId}/thumbnail.jpg`;

        const resolvedThumbnail = finalThumbnail || bunnyThumb;

        // ── Step 4: Save to Firestore ───────────────────────────────────────
        await this.savePublishedVideo({
          user,
          title,
          category,
          tags,
          description,
          videoSrc: hlsUrl,       // primary: HLS stream
          originalUrl: embedUrl,  // fallback: embed player
          isEmbed: false,
          storageType: "bunny_stream",
          storagePath: videoId,   // store videoId for future management
          thumbnail: resolvedThumbnail,
          duration: this.detectedDuration,
          durationFormatted: this.formatDuration(this.detectedDuration),
          toastMessage: "🎉 Video uploaded and ready to stream!"
        });

      } catch (err) {
        console.error("Upload error:", err);
        if (err.message !== "Upload cancelled.") {
          window.showToast("Upload failed: " + (err.message || "Please check your connection."));
        }
      } finally {
        this.isUploading = false;
        this.uploadTask = null;
        if (submitBtn) {
          submitBtn.disabled = false;
          submitBtn.textContent = "Upload Video";
        }
      }

      return;
    }

    // ------------------------------------------------------------------------
    // CASE 2: Embed Video Link (Iframe Protocol)
    // ------------------------------------------------------------------------
    const rawUrl = document.getElementById("uploadVideoUrl")?.value.trim();
    if (!rawUrl) {
      window.showToast("Please provide a video link or embed URL");
      return;
    }

    const parsed = this.parseEmbedUrl(rawUrl);
    const finalVideoSrc = parsed.embedUrl;
    const finalThumbnail = customThumbUrl || this.selectedThumbnailUrl || parsed.defaultThumbnail || window.generateAutoThumbnail(title, category);

    if (submitBtn) {
      submitBtn.disabled = true;
      submitBtn.textContent = "Publishing embed...";
    }

    try {
      await this.savePublishedVideo({
        user,
        title,
        category,
        tags,
        description: description || `Embedded from ${parsed.providerName} by ${user.displayName || "Creator"} on Mero.`,
        videoSrc: finalVideoSrc,
        originalUrl: rawUrl,
        isEmbed: parsed.isEmbed,
        storageType: "embed",
        embedProvider: parsed.provider,
        thumbnail: finalThumbnail,
        duration: this.detectedDuration,
        durationFormatted: "Stream",
        toastMessage: `🎉 ${parsed.providerName} stream published via iframe!`
      });
    } catch (err) {
      console.error("Embed publish failed:", err);
      window.showToast("Failed to embed video. Please try again.");
    } finally {
      if (submitBtn) {
        submitBtn.disabled = false;
        submitBtn.textContent = "Embed & Publish Video";
      }
    }
  }

  async handleStorageUploadFallback({ storageError, user, file, title, category, description, finalThumbnail }) {
    // Local blob fallback: only used during development/testing when Bunny is unreachable
    const errorMsg = storageError?.message || "Storage service error";
    console.log("Storage fallback triggered:", errorMsg);
    window.showToast("Upload error — falling back to local preview: " + errorMsg);

    const localVideoUrl = URL.createObjectURL(file);
    await this.savePublishedVideo({
      user,
      title,
      category,
      description: description || `Uploaded file: ${file.name}`,
      videoSrc: localVideoUrl,
      originalUrl: file.name,
      isEmbed: false,
      storageType: "local_blob",
      storagePath: "",
      thumbnail: finalThumbnail,
      duration: this.detectedDuration,
      durationFormatted: this.formatDuration(this.detectedDuration),
      toastMessage: "⚠️ Local preview only — Bunny Stream unavailable."
    });
  }

  async savePublishedVideo(config) {
    const {
      user,
      title,
      category,
      tags = [],
      description,
      videoSrc,
      originalUrl,
      isEmbed,
      storageType,
      storagePath,
      embedProvider,
      thumbnail,
      duration,
      durationFormatted,
      toastMessage
    } = config;

    const userPhoto = user.photoURL || `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(user.displayName || user.email)}&backgroundColor=6366f1,06b6d4`;

    const newVideo = await window.meroDb.createVideo({
      title,
      category,
      tags: Array.isArray(tags) ? tags : [],
      videoSrc,
      originalUrl,
      isEmbed: !!isEmbed,
      storageType: storageType || (isEmbed ? "embed" : "firebase"),
      storagePath: storagePath || "",
      embedProvider: embedProvider || (isEmbed ? "iframe" : "direct"),
      thumbnail,
      duration: duration || 120,
      durationFormatted: durationFormatted || "Stream",
      channel: {
        id: user.uid,
        name: user.displayName || user.email.split("@")[0],
        avatar: userPhoto
      },
      description,
      chapters: this.parseChaptersFromDescription(description)
    });

    // Add to memory list
    if (window.MERO_VIDEOS) {
      window.MERO_VIDEOS.unshift(newVideo);
    }

    window.showToast(toastMessage || "🎉 Video published successfully!");
    this.isUploading = false;
    this.uploadTask = null;
    this.closeModal();

    // Refresh feed & chips so the new video and tags appear
    if (window.meroFeed) {
      if (typeof window.meroFeed.renderCategoryChips === "function") {
        window.meroFeed.renderCategoryChips();
      }
      window.meroFeed.renderFeed();
    }

    // Navigate directly to the new video's watch page
    if (window.meroApp && newVideo?.id) {
      window.meroApp.openWatchPage(newVideo.id);
    } else if (window.meroApp) {
      window.meroApp.navigateTo("home");
    }
  }

  formatFileSize(bytes) {
    if (!bytes || bytes === 0) return "0 MB";
    const mb = bytes / (1024 * 1024);
    if (mb < 1) {
      return `${(bytes / 1024).toFixed(0)} KB`;
    }
    return `${mb.toFixed(1)} MB`;
  }

  formatDuration(sec) {
    if (!sec || isNaN(sec)) return "0:00";
    const m = Math.floor(sec / 60);
    const s = Math.floor(sec % 60);
    return `${m}:${s < 10 ? "0" : ""}${s}`;
  }

  parseChaptersFromDescription(text) {
    if (!text) return [];
    const lines = text.split("\n");
    const chapters = [];
    const timeRegex = /(?:(\d{1,2}):)?(\d{1,2}):(\d{2})/;

    lines.forEach(line => {
      const match = line.match(timeRegex);
      if (match) {
        const fullMatch = match[0];
        const parts = fullMatch.split(":").map(Number);
        let seconds = 0;
        if (parts.length === 3) {
          seconds = parts[0] * 3600 + parts[1] * 60 + parts[2];
        } else {
          seconds = parts[0] * 60 + parts[1];
        }
        const title = line.replace(fullMatch, "").replace(/^[\s\-–—:]+/, "").trim() || "Chapter";
        chapters.push({ time: seconds, title });
      }
    });

    return chapters;
  }
}

export const meroUpload = new MeroUploadManager();
window.meroUpload = meroUpload;
window.openUploadModal = () => meroUpload.handleUploadTrigger();
window.closeUploadModal = () => meroUpload.closeModal();

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", () => {
    meroUpload.init();
  });
} else {
  meroUpload.init();
}
