/* ==========================================================================
   Mero Upload Content Studio (Dual Mode)
   1. Direct File Upload -> Firebase Storage & Custom Cinematic Player
   2. Embed Stream Link  -> Zero-Host Iframe Protocol (YouTube/Vimeo/Dailymotion)
   ========================================================================== */

import { storage } from "./firebase.js";
import { 
  ref, 
  uploadBytesResumable, 
  getDownloadURL 
} from "firebase/storage";

class MeroUploadManager {
  constructor() {
    this.modal = null;
    this.form = null;
    this.currentMode = "file"; // "file" | "embed"
    this.selectedVideoFile = null;
    this.autoGeneratedThumbnail = "";
    this.detectedDuration = 120;
    this.uploadTask = null;
    this.isUploading = false;
  }

  init() {
    this.modal = document.getElementById("uploadModal");
    this.form = document.getElementById("uploadForm");
    this.bindEvents();
    this.switchMode("file");
  }

  bindEvents() {
    // Global Studio & Upload Triggers
    const triggerIds = ["topUploadBtn", "sidebarStudioBtn", "mobileUploadBtn", "dropdownUploadBtn"];
    triggerIds.forEach(id => {
      const btn = document.getElementById(id);
      if (btn) {
        btn.addEventListener("click", (e) => {
          e.preventDefault();
          this.handleUploadTrigger();
        });
      }
    });

    // Mode Switcher Tabs
    const tabUploadFile = document.getElementById("tabUploadFile");
    const tabEmbedLink = document.getElementById("tabEmbedLink");

    if (tabUploadFile) {
      tabUploadFile.addEventListener("click", () => this.switchMode("file"));
    }
    if (tabEmbedLink) {
      tabEmbedLink.addEventListener("click", () => this.switchMode("embed"));
    }

    // Modal Close
    const closeBtn = document.getElementById("uploadModalCloseBtn");
    if (closeBtn && this.modal) {
      closeBtn.addEventListener("click", () => this.closeModal());
    }

    if (this.modal) {
      this.modal.addEventListener("click", (e) => {
        if (e.target === this.modal && !this.isUploading) this.closeModal();
      });
    }

    // Dropzone & File Selection
    const dropzone = document.getElementById("uploadDropzone");
    const fileInput = document.getElementById("uploadVideoFile");
    const clearFileBtn = document.getElementById("clearFileBtn");

    if (dropzone && fileInput) {
      dropzone.addEventListener("click", (e) => {
        if (!e.target.closest("#clearFileBtn") && !this.isUploading) {
          fileInput.click();
        }
      });

      // Drag & drop
      ["dragenter", "dragover"].forEach(evtName => {
        dropzone.addEventListener(evtName, (e) => {
          e.preventDefault();
          e.stopPropagation();
          if (!this.isUploading) dropzone.classList.add("dragover");
        });
      });

      ["dragleave", "drop"].forEach(evtName => {
        dropzone.addEventListener(evtName, (e) => {
          e.preventDefault();
          e.stopPropagation();
          dropzone.classList.remove("dragover");
        });
      });

      dropzone.addEventListener("drop", (e) => {
        if (this.isUploading) return;
        const files = e.dataTransfer?.files;
        if (files && files.length > 0) {
          this.handleFileSelected(files[0]);
        }
      });

      fileInput.addEventListener("change", (e) => {
        if (e.target.files && e.target.files.length > 0) {
          this.handleFileSelected(e.target.files[0]);
        }
      });
    }

    if (clearFileBtn) {
      clearFileBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.clearSelectedFile();
      });
    }

    // Embed URL Provider Detection & Auto Thumbnail Fetch
    const urlInput = document.getElementById("uploadVideoUrl");
    const providerPill = document.getElementById("urlProviderPill");
    const urlSubhint = document.getElementById("urlSubhint");
    const thumbInput = document.getElementById("uploadThumbUrl");

    if (urlInput) {
      urlInput.addEventListener("input", (e) => {
        const val = e.target.value.trim();
        if (!val) {
          if (providerPill) providerPill.style.display = "none";
          if (urlSubhint) urlSubhint.textContent = "Supports YouTube, Vimeo, Dailymotion, or public iframe embed streams";
          return;
        }

        const parsed = this.parseEmbedUrl(val);
        if (providerPill) {
          providerPill.textContent = parsed.providerName;
          providerPill.className = `provider-pill ${parsed.provider}`;
          providerPill.style.display = "inline-flex";
        }
        if (urlSubhint) {
          urlSubhint.textContent = `✓ Stream will be rendered securely via ${parsed.providerName} iframe embed`;
        }

        // Auto-populate thumbnail if empty and provider has a default poster
        if (parsed.defaultThumbnail && thumbInput && !thumbInput.value) {
          thumbInput.value = parsed.defaultThumbnail;
        }
      });
    }

    // Form Submit
    if (this.form) {
      this.form.addEventListener("submit", (e) => this.handleSubmit(e));
    }
  }

  switchMode(mode) {
    this.currentMode = mode;
    const tabUploadFile = document.getElementById("tabUploadFile");
    const tabEmbedLink = document.getElementById("tabEmbedLink");
    const panelUpload = document.getElementById("studioUploadPanel");
    const panelEmbed = document.getElementById("studioEmbedPanel");
    const submitBtn = document.getElementById("uploadSubmitBtn");
    const urlInput = document.getElementById("uploadVideoUrl");

    if (mode === "file") {
      if (tabUploadFile) {
        tabUploadFile.classList.add("active");
        tabUploadFile.setAttribute("aria-selected", "true");
      }
      if (tabEmbedLink) {
        tabEmbedLink.classList.remove("active");
        tabEmbedLink.setAttribute("aria-selected", "false");
      }
      if (panelUpload) panelUpload.style.display = "flex";
      if (panelEmbed) panelEmbed.style.display = "none";
      if (urlInput) urlInput.removeAttribute("required");
      if (submitBtn && !this.isUploading) {
        submitBtn.textContent = "Upload & Publish Video";
      }
    } else {
      if (tabEmbedLink) {
        tabEmbedLink.classList.add("active");
        tabEmbedLink.setAttribute("aria-selected", "true");
      }
      if (tabUploadFile) {
        tabUploadFile.classList.remove("active");
        tabUploadFile.setAttribute("aria-selected", "false");
      }
      if (panelEmbed) panelEmbed.style.display = "flex";
      if (panelUpload) panelUpload.style.display = "none";
      if (urlInput) urlInput.setAttribute("required", "required");
      if (submitBtn && !this.isUploading) {
        submitBtn.textContent = "Embed & Publish Video";
      }
    }
  }

  handleFileSelected(file) {
    if (!file) return;

    // Validate video file
    const isVideo = file.type.startsWith("video/") || /\.(mp4|webm|mov|ogg|m4v)$/i.test(file.name);
    if (!isVideo) {
      window.showToast("Please choose a valid video file (.mp4, .webm, .mov)");
      return;
    }

    this.selectedVideoFile = file;

    // Display selected file card
    const emptyState = document.getElementById("dropzoneEmptyState");
    const selectedState = document.getElementById("dropzoneSelectedFile");
    const nameEl = document.getElementById("selectedFileName");
    const metaEl = document.getElementById("selectedFileMeta");

    if (emptyState) emptyState.style.display = "none";
    if (selectedState) selectedState.style.display = "flex";
    if (nameEl) nameEl.textContent = file.name;
    if (metaEl) metaEl.textContent = `${this.formatFileSize(file.size)} • Reading media metadata...`;

    // Auto-fill title if empty
    const titleInput = document.getElementById("uploadTitle");
    if (titleInput && !titleInput.value.trim()) {
      const cleanName = file.name
        .replace(/\.[^/.]+$/, "")
        .replace(/[-_]+/g, " ")
        .replace(/\b\w/g, l => l.toUpperCase());
      titleInput.value = cleanName;
    }

    // Extract video duration and capture thumbnail frame via ephemeral video element
    this.extractVideoMetadata(file);
  }

  clearSelectedFile() {
    this.selectedVideoFile = null;
    this.autoGeneratedThumbnail = "";
    const fileInput = document.getElementById("uploadVideoFile");
    if (fileInput) fileInput.value = "";

    const emptyState = document.getElementById("dropzoneEmptyState");
    const selectedState = document.getElementById("dropzoneSelectedFile");
    if (emptyState) emptyState.style.display = "flex";
    if (selectedState) selectedState.style.display = "none";

    const thumbInput = document.getElementById("uploadThumbUrl");
    if (thumbInput && thumbInput.placeholder.includes("Frame captured")) {
      thumbInput.placeholder = "Auto-captured from video frame, YouTube poster, or custom URL";
    }
  }

  extractVideoMetadata(file) {
    const tempUrl = URL.createObjectURL(file);
    const tempVideo = document.createElement("video");
    tempVideo.preload = "metadata";
    tempVideo.src = tempUrl;
    tempVideo.muted = true;
    tempVideo.playsInline = true;

    tempVideo.onloadedmetadata = () => {
      const dur = tempVideo.duration || 120;
      this.detectedDuration = Math.round(dur);
      const metaEl = document.getElementById("selectedFileMeta");
      if (metaEl) {
        metaEl.textContent = `${this.formatFileSize(file.size)} • ${this.formatDuration(dur)}`;
      }

      // Seek to 1s or midpoint to capture a crisp thumbnail frame
      tempVideo.currentTime = Math.min(1.5, dur / 2);
    };

    tempVideo.onseeked = () => {
      try {
        const canvas = document.createElement("canvas");
        canvas.width = tempVideo.videoWidth || 640;
        canvas.height = tempVideo.videoHeight || 360;
        const ctx = canvas.getContext("2d");
        ctx.drawImage(tempVideo, 0, 0, canvas.width, canvas.height);
        this.autoGeneratedThumbnail = canvas.toDataURL("image/jpeg", 0.85);

        const thumbInput = document.getElementById("uploadThumbUrl");
        if (thumbInput && !thumbInput.value) {
          thumbInput.placeholder = "✓ Frame captured from video! (or enter custom image URL)";
        }
      } catch (err) {
        console.warn("Could not capture video frame thumbnail:", err);
      } finally {
        URL.revokeObjectURL(tempUrl);
      }
    };

    tempVideo.onerror = () => {
      URL.revokeObjectURL(tempUrl);
    };
  }

  parseEmbedUrl(url) {
    if (!url) return { isEmbed: true, provider: "iframe", providerName: "Web Embed", embedUrl: "" };
    url = url.trim();

    // YouTube: watch?v=ID, youtu.be/ID, shorts/ID, embed/ID
    const ytMatch = url.match(/(?:youtube\.com\/(?:watch\?v=|embed\/|shorts\/|v\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/i);
    if (ytMatch && ytMatch[1]) {
      const id = ytMatch[1];
      return {
        isEmbed: true,
        provider: "youtube",
        providerName: "YouTube",
        videoId: id,
        embedUrl: `https://www.youtube-nocookie.com/embed/${id}?autoplay=1&enablejsapi=1&rel=0`,
        defaultThumbnail: `https://img.youtube.com/vi/${id}/hqdefault.jpg`
      };
    }

    // Vimeo: vimeo.com/ID
    const vimeoMatch = url.match(/vimeo\.com\/(?:video\/)?(\d+)/i);
    if (vimeoMatch && vimeoMatch[1]) {
      const id = vimeoMatch[1];
      return {
        isEmbed: true,
        provider: "vimeo",
        providerName: "Vimeo",
        videoId: id,
        embedUrl: `https://player.vimeo.com/video/${id}?autoplay=1`,
        defaultThumbnail: ""
      };
    }

    // Dailymotion: dailymotion.com/video/ID
    const dmMatch = url.match(/dailymotion\.com\/video\/([a-zA-Z0-9]+)/i);
    if (dmMatch && dmMatch[1]) {
      const id = dmMatch[1];
      return {
        isEmbed: true,
        provider: "dailymotion",
        providerName: "Dailymotion",
        videoId: id,
        embedUrl: `https://www.dailymotion.com/embed/video/${id}?autoplay=1`,
        defaultThumbnail: `https://www.dailymotion.com/thumbnail/video/${id}`
      };
    }

    // Direct MP4 / WebM video link
    if (/\.(mp4|webm|ogg|m3u8)(\?.*)?$/i.test(url)) {
      return {
        isEmbed: false,
        provider: "direct",
        providerName: "Direct Stream",
        embedUrl: url,
        defaultThumbnail: ""
      };
    }

    // Generic iframe embed URL
    return {
      isEmbed: true,
      provider: "iframe",
      providerName: "Iframe Embed",
      embedUrl: url,
      defaultThumbnail: ""
    };
  }

  handleUploadTrigger() {
    const user = window.meroAuth?.currentUser;
    if (!user) {
      window.meroAuth?.openAuthModal(
        "Please sign in to upload videos to Firebase Storage or publish embed links.",
        () => this.openModal()
      );
      return;
    }
    this.openModal();
  }

  openModal() {
    if (this.modal) this.modal.classList.add("active");
  }

  closeModal() {
    if (this.isUploading) {
      if (!confirm("An upload is currently in progress. Do you want to cancel?")) {
        return;
      }
      if (this.uploadTask) {
        this.uploadTask.cancel();
      }
      this.isUploading = false;
    }

    if (this.modal) this.modal.classList.remove("active");
    if (this.form) this.form.reset();
    this.clearSelectedFile();
    this.hideProgressBar();

    const providerPill = document.getElementById("urlProviderPill");
    if (providerPill) providerPill.style.display = "none";
    const urlSubhint = document.getElementById("urlSubhint");
    if (urlSubhint) urlSubhint.textContent = "Supports YouTube, Vimeo, Dailymotion, or public iframe embed streams";
  }

  showProgressBar() {
    const bar = document.getElementById("uploadProgressContainer");
    if (bar) bar.style.display = "flex";
  }

  hideProgressBar() {
    const bar = document.getElementById("uploadProgressContainer");
    const fill = document.getElementById("uploadProgressBarFill");
    const percent = document.getElementById("uploadProgressPercent");
    if (bar) bar.style.display = "none";
    if (fill) fill.style.width = "0%";
    if (percent) percent.textContent = "0%";
  }

  updateProgress(percentValue, transferred, total) {
    const fill = document.getElementById("uploadProgressBarFill");
    const percentEl = document.getElementById("uploadProgressPercent");
    const statusEl = document.getElementById("uploadProgressStatus");

    const pct = Math.min(100, Math.max(0, Math.round(percentValue)));
    if (fill) fill.style.width = `${pct}%`;
    if (percentEl) percentEl.textContent = `${pct}%`;
    if (statusEl && total > 0) {
      statusEl.innerHTML = `
        <svg class="icon spin" style="width: 14px; height: 14px;" viewBox="0 0 24 24"><line x1="12" y1="2" x2="12" y2="6"></line><line x1="12" y1="18" x2="12" y2="22"></line><line x1="4.93" y1="4.93" x2="7.76" y2="7.76"></line><line x1="16.24" y1="16.24" x2="19.07" y2="19.07"></line><line x1="2" y1="12" x2="6" y2="12"></line><line x1="18" y1="12" x2="22" y2="12"></line><line x1="4.93" y1="19.07" x2="7.76" y2="16.24"></line><line x1="16.24" y1="7.76" x2="19.07" y2="4.93"></line></svg>
        <span>Uploading: ${(transferred / (1024 * 1024)).toFixed(1)} MB / ${(total / (1024 * 1024)).toFixed(1)} MB (${pct}%)</span>
      `;
    }
  }

  async handleSubmit(e) {
    e.preventDefault();
    const user = window.meroAuth?.currentUser;
    if (!user) {
      window.meroAuth?.openAuthModal();
      return;
    }

    const title = document.getElementById("uploadTitle")?.value.trim();
    const category = document.getElementById("uploadCategory")?.value || "General";
    const description = document.getElementById("uploadDescription")?.value.trim() || "";
    const customThumbUrl = document.getElementById("uploadThumbUrl")?.value.trim();
    const submitBtn = document.getElementById("uploadSubmitBtn");

    if (!title) {
      window.showToast("Please enter a video title");
      return;
    }

    // ------------------------------------------------------------------------
    // CASE 1: File Upload (Firebase Storage)
    // ------------------------------------------------------------------------
    if (this.currentMode === "file") {
      if (!this.selectedVideoFile) {
        window.showToast("Please choose or drag a video file to upload");
        return;
      }

      const file = this.selectedVideoFile;
      const finalThumbnail = customThumbUrl || this.autoGeneratedThumbnail || window.generateAutoThumbnail(title, category);

      this.isUploading = true;
      if (submitBtn) {
        submitBtn.disabled = true;
        submitBtn.textContent = "Uploading video...";
      }
      this.showProgressBar();

      // Clean file name
      const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "_");
      const storagePath = `videos/${user.uid}/${Date.now()}_${safeName}`;
      const videoStorageRef = ref(storage, storagePath);

      try {
        const metadata = {
          contentType: file.type || "video/mp4",
          customMetadata: {
            uploadedBy: user.uid,
            creatorName: user.displayName || user.email || "Creator",
            originalName: file.name
          }
        };

        this.uploadTask = uploadBytesResumable(videoStorageRef, file, metadata);

        await new Promise((resolve, reject) => {
          this.uploadTask.on(
            "state_changed",
            (snapshot) => {
              const progress = (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
              this.updateProgress(progress, snapshot.bytesTransferred, snapshot.totalBytes);
            },
            (error) => {
              reject(error);
            },
            async () => {
              try {
                const downloadURL = await getDownloadURL(this.uploadTask.snapshot.ref);
                resolve(downloadURL);
              } catch (urlErr) {
                reject(urlErr);
              }
            }
          );
        }).then(async (downloadURL) => {
          // Video upload succeeded! Save record in Firestore
          await this.savePublishedVideo({
            user,
            title,
            category,
            description,
            videoSrc: downloadURL,
            originalUrl: downloadURL,
            isEmbed: false,
            storageType: "firebase",
            storagePath,
            thumbnail: finalThumbnail,
            duration: this.detectedDuration,
            durationFormatted: this.formatDuration(this.detectedDuration),
            toastMessage: "🎉 Video uploaded and published successfully!"
          });
        }).catch(async (storageError) => {
          console.warn("Firebase Storage upload exception:", storageError);
          // If Firebase Storage is not yet provisioned/configured in user's Firebase console,
          // provide friendly feedback and allow local preview fallback for smooth testing.
          this.handleStorageUploadFallback({
            storageError,
            user,
            file,
            title,
            category,
            description,
            finalThumbnail
          });
        });

      } catch (err) {
        console.error("Upload error:", err);
        window.showToast("Upload failed: " + (err.message || "Please check connection."));
      } finally {
        this.isUploading = false;
        if (submitBtn) {
          submitBtn.disabled = false;
          submitBtn.textContent = "Upload & Publish Video";
        }
      }

      return;
    }

    // ------------------------------------------------------------------------
    // CASE 2: Embed Video Link (Iframe Protocol)
    // ------------------------------------------------------------------------
    const rawUrl = document.getElementById("uploadVideoUrl")?.value.trim();
    if (!rawUrl) {
      window.showToast("Please provide a video link or embed URL");
      return;
    }

    const parsed = this.parseEmbedUrl(rawUrl);
    const finalVideoSrc = parsed.embedUrl;
    const finalThumbnail = customThumbUrl || parsed.defaultThumbnail || window.generateAutoThumbnail(title, category);

    if (submitBtn) {
      submitBtn.disabled = true;
      submitBtn.textContent = "Publishing embed...";
    }

    try {
      await this.savePublishedVideo({
        user,
        title,
        category,
        description: description || `Embedded from ${parsed.providerName} by ${user.displayName || "Creator"} on Mero.`,
        videoSrc: finalVideoSrc,
        originalUrl: rawUrl,
        isEmbed: parsed.isEmbed,
        storageType: "embed",
        embedProvider: parsed.provider,
        thumbnail: finalThumbnail,
        duration: this.detectedDuration,
        durationFormatted: "Stream",
        toastMessage: `🎉 ${parsed.providerName} stream published via iframe!`
      });
    } catch (err) {
      console.error("Embed publish failed:", err);
      window.showToast("Failed to embed video. Please try again.");
    } finally {
      if (submitBtn) {
        submitBtn.disabled = false;
        submitBtn.textContent = "Embed & Publish Video";
      }
    }
  }

  async handleStorageUploadFallback({ storageError, user, file, title, category, description, finalThumbnail }) {
    const errorMsg = storageError?.message || "Storage service error";
    console.log("Storage error details:", errorMsg);

    const isBucketOrPerm = storageError?.code === "storage/bucket-not-found" || 
                           storageError?.code === "storage/unauthorized" ||
                           storageError?.code === "storage/unknown";

    if (isBucketOrPerm) {
      window.showToast("Notice: Cloud storage not configured yet. Saving for local playback preview!");
    } else {
      window.showToast("Upload error: " + errorMsg);
    }

    // Create local object URL for instant preview without blocking developer testing
    const localVideoUrl = URL.createObjectURL(file);
    await this.savePublishedVideo({
      user,
      title,
      category,
      description: description || `Uploaded file: ${file.name}`,
      videoSrc: localVideoUrl,
      originalUrl: file.name,
      isEmbed: false,
      storageType: "local_blob",
      storagePath: "",
      thumbnail: finalThumbnail,
      duration: this.detectedDuration,
      durationFormatted: this.formatDuration(this.detectedDuration),
      toastMessage: "🎉 Video file ready! Playing in Mero Cinema Player."
    });
  }

  async savePublishedVideo(config) {
    const {
      user,
      title,
      category,
      description,
      videoSrc,
      originalUrl,
      isEmbed,
      storageType,
      storagePath,
      embedProvider,
      thumbnail,
      duration,
      durationFormatted,
      toastMessage
    } = config;

    const userPhoto = user.photoURL || `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(user.displayName || user.email)}&backgroundColor=6366f1,06b6d4`;

    const newVideo = await window.meroDb.createVideo({
      title,
      category,
      videoSrc,
      originalUrl,
      isEmbed: !!isEmbed,
      storageType: storageType || (isEmbed ? "embed" : "firebase"),
      storagePath: storagePath || "",
      embedProvider: embedProvider || (isEmbed ? "iframe" : "direct"),
      thumbnail,
      duration: duration || 120,
      durationFormatted: durationFormatted || "Stream",
      channel: {
        id: user.uid,
        name: user.displayName || user.email.split("@")[0],
        avatar: userPhoto
      },
      description,
      chapters: this.parseChaptersFromDescription(description)
    });

    // Add to memory list
    if (window.MERO_VIDEOS) {
      window.MERO_VIDEOS.unshift(newVideo);
    }

    window.showToast(toastMessage || "🎉 Video published successfully!");
    this.closeModal();

    // Refresh feed
    if (window.meroFeed) {
      window.meroFeed.renderFeed();
    }

    // Navigate to watch view immediately if it was a file upload, or home
    if (window.meroApp) {
      window.meroApp.navigateTo("home");
    }
  }

  formatFileSize(bytes) {
    if (!bytes || bytes === 0) return "0 MB";
    const mb = bytes / (1024 * 1024);
    if (mb < 1) {
      return `${(bytes / 1024).toFixed(0)} KB`;
    }
    return `${mb.toFixed(1)} MB`;
  }

  formatDuration(sec) {
    if (!sec || isNaN(sec)) return "0:00";
    const m = Math.floor(sec / 60);
    const s = Math.floor(sec % 60);
    return `${m}:${s < 10 ? "0" : ""}${s}`;
  }

  parseChaptersFromDescription(text) {
    if (!text) return [];
    const lines = text.split("\n");
    const chapters = [];
    const timeRegex = /(?:(\d{1,2}):)?(\d{1,2}):(\d{2})/;

    lines.forEach(line => {
      const match = line.match(timeRegex);
      if (match) {
        const fullMatch = match[0];
        const parts = fullMatch.split(":").map(Number);
        let seconds = 0;
        if (parts.length === 3) {
          seconds = parts[0] * 3600 + parts[1] * 60 + parts[2];
        } else {
          seconds = parts[0] * 60 + parts[1];
        }
        const title = line.replace(fullMatch, "").replace(/^[\s\-–—:]+/, "").trim() || "Chapter";
        chapters.push({ time: seconds, title });
      }
    });

    return chapters;
  }
}

export const meroUpload = new MeroUploadManager();
window.meroUpload = meroUpload;

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", () => {
    meroUpload.init();
  });
} else {
  meroUpload.init();
}
